Product Management Assignment/ProductManagementMVC/ProductManagementMVC/Controllers/LoginController.cs
using ProductManagementMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Formatting;

namespace ProductManagementMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly string _ApiServer = ConfigurationManager.AppSettings["ApiAddress"].ToString();

        // GET: Login
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Login user)
        {
            using(var client = new HttpClient())
            {
                client.BaseAddress= new Uri(_ApiServer);
                var model = new ProductManagementModels.Login
                {
                    Password = user.Password,
                    UserName = user.UserName
                };
                var result = client.PostAsync("Login/Authenticate", user, new JsonMediaTypeFormatter()).Result;
                    
                if(result.IsSuccessStatusCode)
                {
                    TempData["MsgType"] = "Success";
                    TempData["Message"] = "Login Sucessful";
                    var userName = result.Content.ReadAsAsync<string>().Result;
                    FormsAuthentication.SetAuthCookie(userName, false);
                    Session["UserName"] = userName;
                    return Redirect("/Product");
                }
                TempData["isSuccess"] = false;
                TempData["Msg"] =  "User Name or Password is Incorrect";
                return RedirectToAction("Index");
            }
        }

        [AllowAnonymous]
        public ActionResult AddUser()
        {
            return View("AddUser");
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult AddUser(User model)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_ApiServer);
                    var entity = new ProductManagementModels.User
                    {
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        login = new ProductManagementModels.Login
                        {
                            UserName = model.UserName,
                            Password = model.Password
                        }
                    };
                    var result = client.PostAsJsonAsync("User/Add", entity).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["isSuccess"] = true;
                        TempData["Msg"] = "Registration Successful";
                        return RedirectToAction("Index");
                    }
                    else
                        ViewBag.Msg = "Registration Failed";
                }
            }
            return View();
        }

        [Authorize]
        public ActionResult Logout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

Product Management Assignment/ProductManagementMVC/ProductManagementMVC/Controllers/ProductController.cs
using ProductManagementMVC.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ProductManagementMVC.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly string _SmallImagePath =  ConfigurationManager.AppSettings["SmallImagePath"].ToString();
        private readonly string _LargeImagePath = ConfigurationManager.AppSettings["LargeImagePath"].ToString();
        private readonly string _ApiServer = ConfigurationManager.AppSettings["ApiAddress"].ToString();
        private static List<ProductListView> products = null;
        private static List<string> CategoryList = null;
        // GET: Product
        public ActionResult Index()
        {
            string userName = Session["UserName"].ToString();
            if (userName == null)
                userName = "Not Found";
            ViewBag.Message = "Welcome " + userName;
            return View();
        }

        public  ActionResult AddProduct()
        {
            using(var client =  new HttpClient())
            {
                client.BaseAddress = new Uri(_ApiServer);
                //int ProductId = client.GetAsync("Products/Id").Result.Content.ReadAsAsync<int>().Result;
                //if (CategoryList == null)
                //{
                //    var list = client.GetAsync("Category/List").Result.Content.ReadAsAsync<List<string>>().Result;
                //    CategoryList = new SelectList(list);
                //}

                var result = client.GetAsync("Products/Id").Result.Content.ReadAsAsync<CategoryResponseViewModel>().Result;
                var CategoryList = new SelectList(result.CategoryList);
                ViewBag.CategoryList=CategoryList;
                ViewBag.Id = result.id;
                return View();
            }
        }

        [HttpPost]
        public ActionResult AddProduct(Product product,HttpPostedFileBase SmallImage,HttpPostedFileBase LargeImage,int ID)
        {

            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_ApiServer);

                    string FileName = ID + "." + Path.GetExtension(SmallImage.FileName);
                    product.SmallImagePath = _SmallImagePath + FileName;

                    if (LargeImage != null)
                    {
                        product.LargeImagePath = _LargeImagePath + ID+"."+Path.GetExtension(LargeImage.FileName);
                    }
                    var model = new ProductManagementModels.Product
                    {
                        Category = product.Category,
                        Name = product.Name,
                        Price = product.Price,
                        Quantity = product.Quantity,
                        ShortDescription = product.ShortDescription,
                        LongDescription = product.LongDescription,
                        SmallImagePath = product.SmallImagePath,
                        LargeImagePath = product.LargeImagePath
                    };
                    var result = client.PostAsJsonAsync("Products/Add", model).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        SmallImage.SaveAs(Server.MapPath(product.SmallImagePath));
                        if (LargeImage != null)
                            LargeImage.SaveAs(Server.MapPath(product.LargeImagePath));
                        TempData["isSuccess"] = true;
                        TempData["MsgTitle"] = "Success!";
                        TempData["Msg"] = product.Name + " Added Successfully";

                    }
                    else
                    {
                        TempData["isSuccess"] = false;
                        TempData["MsgTitle"] = "Failure!";
                        TempData["Msg"] = product.Name + "Not Added";
                    }

                    //Reflect newly added product in the Local ProductList
                    GetProductList();
                    return RedirectToAction("AddProduct");
                }
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_ApiServer);
                //int ProductId = client.GetAsync("Products/Id").Result.Content.ReadAsAsync<int>().Result;
                //if (CategoryList == null)
                //{
                //    var list = client.GetAsync("Category/List").Result.Content.ReadAsAsync<List<string>>().Result;
                //    CategoryList = new SelectList(list);
                //}

                var result = client.GetAsync("Products/Id").Result.Content.ReadAsAsync<CategoryResponseViewModel>().Result;
                var CategoryList = new SelectList(result.CategoryList);
                ViewBag.CategoryList = CategoryList;
                ViewBag.Id = result.id;
                return View();
            }
        }

        public ActionResult EditProduct(string searchString,string sortOrder, string currentFilter, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (products == null)
            {
                //Prolem Occured while fetching list
                if (!GetProductList())

                    return View();
            }

            //Temporary list for search and sort results
            var tempList = products;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PricesortParm = sortOrder == "price" ? "price_desc" : "price";
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                tempList = products.Where(product=> product.Name.ToLower().Contains(searchString)).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    tempList = tempList.OrderByDescending(product => product.Name).ToList();
                    break;
                case "price":
                    tempList = tempList.OrderBy(product => product.Price).ToList();
                    break;
                case "price_desc":
                    tempList = tempList.OrderByDescending(product => product.Price).ToList();
                    break;
                default:
                    tempList = tempList.OrderBy(product => product.Name).ToList();
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(tempList.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult DeleteProduct(int id)
        {
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_ApiServer);
                var result = client.DeleteAsync("Products/Delete/" + id).Result;
                if (result.IsSuccessStatusCode)
                {
                    var product = result.Content.ReadAsAsync<ProductManagementModels.Product>().Result;
                    var SmallImage = Server.MapPath(product.SmallImagePath);
                    System.IO.File.Delete(SmallImage);
                    if (product.LargeImagePath != null)
                        System.IO.File.Delete(Server.MapPath(product.LargeImagePath));
                    
                    TempData["isSuccess"] = true;
                    TempData["Msg"] = product.Name + " Remove Successfully!";
                } else
                {
                    TempData["isSuccess"] = false;
                    TempData["Msg"] = "Delete Failed!";
                }
            }
            GetProductList();
            return RedirectToAction("EditProduct");
        }

        [ActionName("Add Category")]
        public ActionResult AddCategory()
        {
            return View("AddCategory");
        }

        [HttpPost]
        [ActionName("Add Category")]
        public ActionResult AddCategory(string category)
        {
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_ApiServer);
                var model = new ProductManagementModels.Category
                {
                    ProductCategory = category
                };
                var result = client.PostAsJsonAsync("Category/Add", model).Result;
                ModelState.Clear();
                TempData["isSuccess"] = true;
                TempData["Msg"] = "Category "+category + " Added Successfully!";
                return RedirectToAction("Add Category");
            }
        }

        public ActionResult UpdateProduct(int id)
        {
            Product product = null;
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_ApiServer);
                var result = client.GetAsync("Products/Get/" + id).Result;
                if(result.IsSuccessStatusCode)
                {
                    var model = result.Content.ReadAsAsync<ProductManagementModels.Product>().Result;
                    product = new Product
                    {
                        Name=model.Name,
                        Category=model.Category,
                        Price=model.Price,
                        Quantity=model.Quantity,
                        ShortDescription=model.ShortDescription,
                        LongDescription=model.LongDescription,
                        SmallImagePath=model.SmallImagePath,
                        LargeImagePath=model.LargeImagePath

Product Management Assignment/ProductManagementMVC/ProductManagementMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <link href="~/Content/sidebar.css" rel="stylesheet" />

</head>
<body>
    <div id="wrapper">
        @if (Request.IsAuthenticated)
        {
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <nav id="spy">
                    <ul class="sidebar-nav nav">
                        <li>
                            @Html.ActionLink("Add new  Product", "AddProduct", "Product")
                        </li>
                        <li>
                            @Html.ActionLink("Edit Product", "EditProduct", "Product")
                        </li>
                        <li>
                            @Html.ActionLink("Add Catgory", "Add Category", "Product")
                        </li>
                    </ul>
                </nav>
            </div>
        }
        <!-- Page content -->
    <div id="page-content-wrapper">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>                   
                    @Html.ActionLink("Product Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (Request.IsAuthenticated)
                        {
                            <li class="nav">@Html.ActionLink("Logout", "Logout", "Login", "", new { @class = "nav navbar-link" })</li>
                        }
                        else
                        {
                            <li class="nav">@Html.ActionLink("Login", "Index", "Login", htmlAttributes: new { @class = "nav navbar-link" })</li>
                        }
                    </ul>
                </div>
            </div>
        </div>

        <div class="page-content inset" data-spy="scroll" data-target="#spy">
            @RenderBody()
            @RenderSection("scripts", required: false)
        </div>
    </div>
    </div>
</body>
</html>

Product Management Assignment/ProductManagementMVC/ProductManagementMVC/Views/Shared/sideBar.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>